# Generated by Django 4.2.5 on 2023-10-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasyncsettings',
            name='sync_frequency',
            field=models.IntegerField(default=60),
        ),
    ]
