# Generated by Django 4.2.5 on 2023-10-22 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0002_alter_datasyncsettings_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasyncsettings',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(9, 8, 5, 911535)),
        ),
    ]
