# Generated by Django 4.2.5 on 2023-10-17 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0002_backupschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasyncsettings',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(11, 52, 7, 114168)),
        ),
    ]
