# Generated by Django 4.2.5 on 2023-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0002_datasyncsettings_sync_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasyncsettings',
            name='folder_url',
        ),
        migrations.RemoveField(
            model_name='datasyncsettings',
            name='sync_frequency',
        ),
        migrations.AddField(
            model_name='datasyncsettings',
            name='data_issues_folder_url',
            field=models.CharField(default='E:/', max_length=500),
        ),
        migrations.AddField(
            model_name='datasyncsettings',
            name='data_sync_frequency',
            field=models.IntegerField(default=60, help_text='In seconds'),
        ),
        migrations.AddField(
            model_name='datasyncsettings',
            name='faclity_list_csv_path',
            field=models.CharField(default='E:/', max_length=500),
        ),
    ]
