# Generated by Django 4.2.5 on 2023-10-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0003_remove_datasyncsettings_folder_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasyncsettings',
            name='data_issues_folder_url',
            field=models.CharField(default='E:/projects/DataIssueTracker/DITApi/media/facility data issues', max_length=500),
        ),
        migrations.AlterField(
            model_name='datasyncsettings',
            name='faclity_list_csv_path',
            field=models.CharField(default='E:/projects/DataIssueTracker/DITApi/media/Hospital ID and Names.xlsx', max_length=500),
        ),
    ]
