# Generated by Django 4.2.5 on 2023-10-17 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0003_alter_datasyncsettings_time_of_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupSchedule',
        ),
        migrations.AlterField(
            model_name='datasyncsettings',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(15, 46, 20, 782511)),
        ),
    ]
