# Generated by Django 4.2.5 on 2023-10-17 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0004_delete_backupschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasyncsettings',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(17, 12, 25, 633852)),
        ),
    ]
