# Generated by Django 4.2.5 on 2023-10-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0005_alter_dataqualityissues_date_of_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityissues',
            name='date_action_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
