# Generated by Django 4.2.5 on 2023-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0006_alter_dataqualityissues_date_action_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityissues',
            name='action_taken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
