# Generated by Django 4.2.5 on 2023-10-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0008_alter_dataqualityissues_inconsistency'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasyncsettings',
            name='data_sync_shedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
