# Generated by Django 4.2.5 on 2023-10-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0009_datasyncsettings_data_sync_shedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityissues',
            name='action_taken',
            field=models.CharField(choices=[('Entry Corrected', 'Entry Corrected'), ('Data Matches Source Document', 'Data Matches Source Document'), ('Data Already Available', 'Data Already Available'), ('No Data Needed', 'No Data Needed'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
