# Generated by Django 4.2.5 on 2023-10-27 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0011_alter_datasyncsettings_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasyncsettings',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(18, 49, 53, 48650)),
        ),
        migrations.AlterField(
            model_name='emailsetup',
            name='email_password',
            field=models.CharField(blank=True, default='T*%mw+t8h~IZY&*2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailsetup',
            name='support_reply_email',
            field=models.EmailField(blank=True, default='info@bengohub.co.ke', max_length=255, null=True),
        ),
    ]
