# Generated by Django 4.2.5 on 2023-10-28 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0012_alter_datasyncsettings_time_of_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasyncsettings',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(9, 31, 31, 251975)),
        ),
    ]
