# Generated by Django 4.2.6 on 2023-12-09 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0015_alter_datasyncsettings_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasyncsettings',
            name='time_of_day',
            field=models.TimeField(default=datetime.time(21, 43, 17, 792142)),
        ),
    ]
