# Generated by Django 4.2.5 on 2023-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', 'seed_users_001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.CharField(default='DQIts', max_length=100),
        ),
    ]
