# Generated by Django 4.2.5 on 2023-10-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', 'seed_users_001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_role',
            new_name='roles',
        ),
    ]
