# Generated by Django 4.2.5 on 2023-10-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device',
            field=models.CharField(default='Phone', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ip_address',
            field=models.CharField(default='192.168.0.1', max_length=100),
        ),
    ]
