# Generated by Django 4.2.5 on 2023-10-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0001_customuser_organisation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
