# Generated by Django 4.2.5 on 2023-10-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0001_rename_user_role_customuser_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='roles',
            new_name='role',
        ),
    ]
