# Generated by Django 4.2.5 on 2023-10-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0002_customuser_device_customuser_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupschedule',
            old_name='mysql_cmd_path',
            new_name='db_backup_cmd',
        ),
    ]
