# Generated by Django 4.2.5 on 2023-10-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupschedule',
            old_name='destination_path',
            new_name='folder_path',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='source_path',
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='mysql_cmd_path',
            field=models.CharField(default='C:\\Program Files\\MySQL\\MySQL Server 8.0\x08in\\mysqldump', help_text='For windows environment', max_length=255),
        ),
    ]
