# Generated by Django 4.2.5 on 2023-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQIT_Endpoint', '0010_alter_dataqualityissues_action_taken'),
        ('DQITAuth', '0002_rename_roles_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facilities_assigned',
            field=models.ManyToManyField(blank=True, null=True, to='DQIT_Endpoint.facilities'),
        ),
    ]
