# Generated by Django 4.2.5 on 2023-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0003_rename_destination_path_backupschedule_folder_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='folder_path',
            field=models.CharField(default='E:\\projects\\DataIssueTracker\\DITApi\\media\x08ackups', max_length=255),
        ),
    ]
