# Generated by Django 4.2.5 on 2023-10-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0003_alter_customuser_facilities_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='+254743793901', max_length=15),
        ),
    ]
