# Generated by Django 4.2.5 on 2023-10-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0005_remove_backupschedule_db_backup_cmd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='folder_path',
            field=models.CharField(default='E:\\projects\\DataIssueTracker\\DITApi\x08ackups', max_length=255),
        ),
    ]
