# Generated by Django 4.2.5 on 2023-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0006_alter_backupschedule_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='folder_path',
            field=models.CharField(default='E:\\projects\\DataIssueTracker\\DITApi\x08ackups', help_text='Backup folder path', max_length=255),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='restore_file',
            field=models.CharField(blank=True, default='E:\\projects\\DataIssueTracker\\DITApi\\media\x08ackups\x08ackup_2023_10_23_15-53-15.sql', help_text='Restore file path', max_length=255, null=True),
        ),
    ]
