# Generated by Django 4.2.5 on 2023-10-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DQITAuth', '0007_alter_backupschedule_folder_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='restore_file',
            field=models.CharField(blank=True, default='E:\\projects\\DataIssueTracker\\DITApi\x08ackups\x08ackup_2023_10_23_15-53-15.sql', help_text='Restore file path', max_length=255, null=True),
        ),
    ]
