version: '3'
services:
  dqitsdb:
    container_name: dqitsdb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dqitsuser
      - MYSQL_PASSWORD=DQITs@123
      - MYSQL_DATABASE=dqits
    image: mysql:8.0
    ports:
      - "3309:3306"
  ditapi:
    container_name: ditapi
    environment:
      - DB_ROOT_PASSWORD=root
      - DB_USER=dqitsuser
      - DB_PASSWORD=DQITs@123
      - DB_NAME=dqits
      - DB_HOST=192.168.251.10
    image: ditapi:latest
    ports:
      - "8001:8000"
    depends_on:
      - dqitsdb
    volumes:
      - /home/titusdev/projects/DataIssueTracker/DITApi/static:/app/static
      - /home/titusdev/projects/DataIssueTracker/DITApi/backups:/app/backups
      - /home/titusdev/projects/DataIssueTracker/DITApi/media:/app/media
      - /home/titusdev/projects/DataIssueTracker/facility data issues:/app/facility data issues
    command: gunicorn DITApi.wsgi:application --bind 0.0.0.0:8000
  ditui:
    image: ditui:latest
    ports:
      - "3000:80"
    depends_on:
      - ditapi
